### ISSUE TITLE
Given a command and username#tag I want to  know  the rank of  the player 

### ISSUE THREAD

**Issue by rokkoo** [rokkoo/valorat-discord-bot#1]
[ ] We need  to get the data  from this api https://docs.henrikdev.xyz/valorant.html
[ ] Createa command  listener  to handle the  player id  passed on  the parameter  params

For example something like `!rank rokkoo#bnt`

**Comment by juancastellano115** [comment]
I will take this 💪

**Comment by rokkoo** [comment]
Sure! @juancastellano115

**Comment by rokkoo** [comment]
Nice joob @juancastellano115 !
